/**
 * Slack Webhook Client
 *
 * 週次レポートをSlackに送信
 */

import https from 'https';

export interface SlackConfig {
  webhookUrl: string;
}

export interface SlackReportData {
  title: string;
  period_start: string;
  period_end: string;
  summary: {
    total_commits: number;
    total_additions: number;
    total_deletions: number;
    active_repos: number;
  };
  repositories: Array<{
    name: string;
    commits: number;
  }>;
}

/**
 * Slackにレポート送信
 */
export async function publishToSlack(
  config: SlackConfig,
  report: SlackReportData
): Promise<void> {
  console.log('📤 Slack送信中...');

  const message = buildSlackMessage(report);

  return new Promise((resolve, reject) => {
    const url = new URL(config.webhookUrl);

    const options = {
      hostname: url.hostname,
      path: url.pathname,
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
    };

    const req = https.request(options, (res) => {
      let data = '';

      res.on('data', (chunk) => {
        data += chunk;
      });

      res.on('end', () => {
        if (res.statusCode === 200) {
          console.log('✅ Slack送信成功');
          resolve();
        } else {
          console.error(`❌ Slack送信失敗: ${res.statusCode}`);
          console.error(`Response: ${data}`);
          reject(new Error(`Slack API error: ${res.statusCode}`));
        }
      });
    });

    req.on('error', (error) => {
      console.error('❌ Slackリクエストエラー:', error);
      reject(error);
    });

    req.write(JSON.stringify(message));
    req.end();
  });
}

/**
 * Slackメッセージを構築
 */
function buildSlackMessage(report: SlackReportData): any {
  const topRepos = report.repositories
    .slice(0, 5)
    .map((r, i) => `${i + 1}. *${r.name}*: ${r.commits} commits`)
    .join('\n');

  return {
    blocks: [
      {
        type: 'header',
        text: {
          type: 'plain_text',
          text: `📊 ${report.title}`,
          emoji: true,
        },
      },
      {
        type: 'section',
        text: {
          type: 'mrkdwn',
          text: `*期間*: ${report.period_start} 〜 ${report.period_end}`,
        },
      },
      {
        type: 'divider',
      },
      {
        type: 'section',
        fields: [
          {
            type: 'mrkdwn',
            text: `*総コミット数*\n${report.summary.total_commits}`,
          },
          {
            type: 'mrkdwn',
            text: `*アクティブリポジトリ*\n${report.summary.active_repos}`,
          },
          {
            type: 'mrkdwn',
            text: `*追加行数*\n+${report.summary.total_additions.toLocaleString()}`,
          },
          {
            type: 'mrkdwn',
            text: `*削除行数*\n-${report.summary.total_deletions.toLocaleString()}`,
          },
        ],
      },
      {
        type: 'divider',
      },
      {
        type: 'section',
        text: {
          type: 'mrkdwn',
          text: `*📦 Top 5 リポジトリ*\n${topRepos}`,
        },
      },
      {
        type: 'context',
        elements: [
          {
            type: 'mrkdwn',
            text: '🤖 Generated by GitHub Activity Aggregator',
          },
        ],
      },
    ],
  };
}
